import type { Teacher } from "../types"

export const mockTeachers: Teacher[] = [
  {
    id: "teacher-001",
    name: "María García",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-002",
    name: "Pierre Dubois",
    title: "French Language Specialist",
    location: "Paris, France",
    rating: 4.8,
    reviewCount: 98,
    hourlyRate: 32,
    languages: ["French", "English"],
    experience: 7,
    studentCount: 110,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Structured and methodical",
    availability: ["Weekdays", "Mornings"],
    specialties: ["French Grammar", "Conversation", "Literature"],
    profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-003",
    name: "Sarah Martinez",
    title: "English, Spanish & French Teacher",
    location: "New York, USA",
    rating: 4.8,
    reviewCount: 127,
    hourlyRate: 45,
    languages: ["English", "Spanish", "French"],
    experience: 8,
    studentCount: 245,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Morning", "Evenings", "Weekend"],
    specialties: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
    profileImage: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-004",
    name: "Sarah Martinez",
    profileImage: "/assets/images/teacher-profile.jpg", // Use local asset
    languages: ["English", "Spanish", "French"],
    rating: 4.8,
    reviewCount: 127,
    isOnline: true,
    isVerified: true,
    experience: 8,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
    title: "English, Spanish",
    location: "",
    hourlyRate: 0,
    studentCount: 0,
    teachingStyle: "",
    availability: [],
    specialties: [],
    isFavorited: false
  },
  {
    id: "teacher-005",
    name: "María García5",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-006",
    name: "Pierre Dubois6",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-007",
    name: "María García7",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-008",
    name: "Pierre Dubois8",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-009",
    name: "María García9",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-010",
    name: "Pierre Dubois10",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-011",
    name: "María García11",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-012",
    name: "Pierre Dubois12",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-013",
    name: "María García13",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-014",
    name: "Pierre Dubois14",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-015",
    name: "María García15",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-016",
    name: "Pierre Dubois16",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-017",
    name: "María García17",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-018",
    name: "Pierre Dubois18",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-019",
    name: "María García19",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-020",
    name: "Pierre Dubois20",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-021",
    name: "María García21",
    title: "Native Spanish Teacher & Cultural Expert",
    location: "San Francisco, USA",
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 25,
    languages: ["Spanish", "English"],
    experience: 8,
    studentCount: 156,
    isVerified: true,
    isOnline: true,
    teachingStyle: "Interactive and conversational",
    availability: ["Weekdays", "Evenings"],
    specialties: ["Beginner Spanish", "Grammar", "Conversation"],
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    isFavorited: false,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
  {
    id: "teacher-022",
    name: "Pierre Dubois22",
    title: "French Language Specialist",
    location: "San Francisco, USA",
    rating: 4.8,
    reviewCount: 89,
    hourlyRate: 30,
    languages: ["French", "English"],
    experience: 6,
    studentCount: 98,
    isVerified: true,
    isOnline: false,
    teachingStyle: "Structured and methodical",
    availability: ["Weekends", "Mornings"],
    specialties: ["French Grammar", "Pronunciation", "Literature"],
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    isFavorited: true,
    bio: `I'm a passionate language educator with over 8 years of experience teaching English, Spanish, and French to students of all ages. My teaching philosophy centers on creating an engaging, supportive environment where students feel confident to practice and make mistakes as part of their learning journey.\n\nI hold a Master's degree in Applied Linguistics and am certified in TESOL/TEFL. I've worked with students from diverse cultural backgrounds, helping them achieve their language goals whether for academic purposes, career advancement, or personal enrichment.\n\nMy courses are interactive and tailored to each student's learning style and objectives. I believe in using real-world materials and practical scenarios to make language learning both effective and enjoyable.`,
    certificates: [
      {
        name: "Master's in Applied Linguistics",
        issuer: "University of California, Berkeley",
        year: "2016",
        verified: true,
      },
      {
        name: "TESOL Certification",
        issuer: "International TESOL Association",
        year: "2015",
        verified: true,
      },
      {
        name: "DELE Spanish Proficiency Certificate",
        issuer: "Instituto Cervantes",
        year: "2014",
        verified: true,
      },
    ],
    ageGroups: ["Children (6-12)", "Teenagers (13-17)", "Adults (18+)", "Seniors (65+)"],
    teachingExperience: [
      {
        position: "Senior Language Instructor",
        institution: "International Language Academy",
        duration: "2019 - Present",
        description: "Teaching advanced English and Spanish courses to international students",
      },
      {
        position: "Online Language Tutor",
        institution: "Global Learning Platform",
        duration: "2017 - 2019",
        description: "Conducted 1-on-1 and group sessions for students worldwide",
      },
      {
        position: "ESL Teacher",
        institution: "Community College District",
        duration: "2015 - 2017",
        description: "Taught English as a Second Language to adult learners",
      },
    ],
    specializations: [
      "Conversational Practice",
      "Business English",
      "Academic Writing",
      "Pronunciation Training",
      "Grammar Fundamentals",
      "Cultural Communication",
    ],
  },
]
