import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HelloK12",
  description: "Generated by HelloK12",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDevelopment = process.env.NODE_ENV === "development";

  return (
    <html lang="en">
      <head>
        {isDevelopment ? (
          <Script id="strip-extension-attrs" strategy="beforeInteractive">
            {`(() => {
                const TARGET_ATTR = "cz-shortcut-listen";
                let bodyObserved = false;
                const removeFromBody = () => {
                  if (document.body?.hasAttribute(TARGET_ATTR)) {
                    document.body.removeAttribute(TARGET_ATTR);
                  }
                };
                const observeBodyAttr = () => {
                  if (!document.body || bodyObserved) return;
                  bodyObserved = true;
                  new MutationObserver((mutations) => {
                    for (const mutation of mutations) {
                      if (mutation.type === "attributes" && mutation.attributeName === TARGET_ATTR) {
                        removeFromBody();
                      }
                    }
                  }).observe(document.body, {
                    attributes: true,
                    attributeFilter: [TARGET_ATTR],
                  });
                };

                removeFromBody();
                observeBodyAttr();

                new MutationObserver(() => {
                  removeFromBody();
                  observeBodyAttr();
                }).observe(document.documentElement, {
                  childList: true,
                  subtree: true,
                  attributes: true,
                  attributeFilter: [TARGET_ATTR],
                });
              })();`}
          </Script>
        ) : null}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <ToastContainer position="top-right" />
      </body>
    </html>
  );
}
